/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TAKAO_TAKAONative */

#ifndef _Included_TAKAO_TAKAONative
#define _Included_TAKAO_TAKAONative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TAKAO_TAKAONative
 * Method:    addPersistenceObject
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_TAKAO_TAKAONative_addPersistenceObject
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     TAKAO_TAKAONative
 * Method:    deletePersistenceObject
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_TAKAO_TAKAONative_deletePersistenceObject
  (JNIEnv *, jobject, jstring);

/*
 * Class:     TAKAO_TAKAONative
 * Method:    getPersistenceObject
 * Signature: (Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_TAKAO_TAKAONative_getPersistenceObject
  (JNIEnv *, jobject, jstring);

/*
 * Class:     TAKAO_TAKAONative
 * Method:    isPersistence
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_TAKAO_TAKAONative_isPersistence
  (JNIEnv *, jobject, jstring);

/*
 * Class:     TAKAO_TAKAONative
 * Method:    clflush
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_TAKAO_TAKAONative_clflush
  (JNIEnv *, jobject, jobject);

/*
 * Class:     TAKAO_TAKAONative
 * Method:    printObjectaddres
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_TAKAO_TAKAONative_printObjectaddres
  (JNIEnv *, jobject, jobject);

/*
 * Class:     TAKAO_TAKAONative
 * Method:    compaddrHashtoRaw
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_TAKAO_TAKAONative_compaddrHashtoRaw
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     TAKAO_TAKAONative
 * Method:    getClass
 * Signature: (Ljava/lang/String;)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_TAKAO_TAKAONative_getClass
  (JNIEnv *, jobject, jstring);

/*
 * Class:     TAKAO_TAKAONative
 * Method:    nilMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TAKAO_TAKAONative_nilMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
